"""
Train and persist the final deployable two-stage cascade model
(RandomForest gate -> XGBoost ranker), replicating the architecture
documented in notebooks/01_fraud_analysis.ipynb (see `run_pipeline`,
cell 28, and the final full-data fit in cell 36) -- with a corrected
Stage-1 gate. See the module docstring on `RF_GATE_PARAMS` below for
the fix and why it's justified.

This script does NOT touch the notebook and does NOT require the raw
Kaggle CSVs -- it trains from the already-cached, notebook-produced
provider-level feature matrix at outputs/features_train.parquet, which
was generated by src/features.py + src/loaders.py and contains both the
31 engineered features and the fraud_label target.

Unlike the notebook (which only ever fits the cascade inside
StratifiedKFold cross-validation, for evaluation purposes), this script
fits ONE final RF gate + ONE final XGBoost ranker on the full training
set, to be persisted as the artifact served by the FastAPI app. It also
runs an honest 5-fold out-of-fold validation of the gate alone (fresh
RF fit per fold, threshold chosen from the *training* fold's OOB scores
only, then applied to the held-out fold) to report a non-circular
recall/precision estimate, and prints a BEFORE vs AFTER comparison
against the original (broken) configuration.

Output:
    outputs/model/cascade_model.joblib
        {
            "rf_gate": fitted RandomForestClassifier,
            "xgb_ranker": fitted XGBClassifier,
            "gate_threshold": float,
            "feature_cols": list[str],
            "gate_target_recall": float,
            "trained_rows": int,
            "positive_rate": float,
            "rf_gate_params": dict,           # hyperparameters actually used
            "gate_eval_full": {...},          # self-consistency stats on full training set
            "gate_eval_cv": {...},            # honest out-of-fold validation stats
        }
    outputs/model/gate_evaluation_report.txt
        Human-readable BEFORE/AFTER report (also printed to stdout).
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier

RNG = 42

ROOT = Path(__file__).resolve().parent.parent
PARQUET = ROOT / "outputs" / "features_train.parquet"
MODEL_DIR = ROOT / "outputs" / "model"
MODEL_PATH = MODEL_DIR / "cascade_model.joblib"
REPORT_PATH = MODEL_DIR / "gate_evaluation_report.txt"

# Same gate-recall target as the notebook (cell 28): retain ~95% of positives.
GATE_TARGET_RECALL = 0.95
GATE_PERCENTILE = int((1 - GATE_TARGET_RECALL) * 100)  # = 5

# --- Stage-1 RandomForest gate hyperparameters -----------------------------
#
# ROOT CAUSE (investigated, not assumed): class_weight="balanced" computes
# sample weights ONCE from the full training set's class ratio and applies
# that same fixed weighting to every tree's bootstrap draw. Combined with
# unconstrained trees (min_samples_leaf=1, no max_depth -> mean depth 22,
# ~241 leaves/tree, grown to full purity), this produced highly extreme,
# bimodal per-tree probability estimates: 44% of the 506 positive providers
# got an OOB fraud-probability of EXACTLY 0.0. Since the gate threshold is
# the 5th percentile of positive OOB scores (to retain 95% recall), and far
# more than 5% of positives already sat at the floor, the threshold resolved
# to 0.0 and the gate passed ~100% of providers through -- a no-op.
#
# FIX (validated via 5-fold out-of-fold grid search across class_weight,
# max_depth, min_samples_leaf, min_samples_split, and n_estimators -- see
# gate evaluation report / conversation record):
#   - class_weight="balanced_subsample": recomputes weights PER TREE from
#     each tree's own bootstrap sample instead of one fixed global weight.
#     This alone cut the zero-OOB rate from ~44% to ~2%.
#   - min_samples_leaf=10: a standard stabilizer that prevents leaves from
#     being built on a handful of samples (which is what let a single
#     unlucky bootstrap draw produce a 100%-pure, zero-evidence leaf). This
#     further cut the zero-OOB rate to ~0.6% and tightened the recall/pass
#     -rate distribution across seeds.
# Confirmed stable across 6 random seeds: 94.7-95.3% out-of-fold recall,
# 25.5-28.3% pass rate (72-74% filtered) -- consistent with the ~72%
# elimination / ~95.3% gate recall documented in README.md, suggesting
# "balanced" (vs "balanced_subsample") was a regression from the intended
# configuration rather than a considered choice.
RF_GATE_PARAMS_BEFORE = dict(
    n_estimators=300,
    class_weight="balanced",
    max_depth=None,
    min_samples_leaf=1,
    min_samples_split=2,
)
RF_GATE_PARAMS = dict(
    n_estimators=300,
    class_weight="balanced_subsample",
    max_depth=None,
    min_samples_leaf=10,
    min_samples_split=2,
)


def _fit_gate(X, y, params, seed=RNG):
    rf = RandomForestClassifier(
        n_jobs=-1, random_state=seed, oob_score=True, **params
    )
    rf.fit(X, y)
    return rf


def _gate_threshold_from_oob(rf, X_train, y_train):
    oob_proba = rf.oob_decision_function_[:, 1]
    pos_oob = oob_proba[y_train == 1]
    threshold = (
        float(np.percentile(pos_oob, GATE_PERCENTILE)) if len(pos_oob) > 0 else 0.0
    )
    return threshold, oob_proba


def _gate_metrics(y_true, passed_mask, n_total):
    """Precision/recall/F1 of the gate treated as a binary classifier
    where 'predicted positive' = 'passed the gate'."""
    tp = int(((y_true == 1) & passed_mask).sum())
    fn = int(((y_true == 1) & ~passed_mask).sum())
    fp = int(((y_true == 0) & passed_mask).sum())
    n_pos = int((y_true == 1).sum())
    n_passed = int(passed_mask.sum())

    recall = tp / n_pos if n_pos else 0.0
    precision = tp / n_passed if n_passed else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0

    return {
        "total_providers": int(n_total),
        "positive_providers": n_pos,
        "providers_passed": n_passed,
        "providers_filtered": int(n_total - n_passed),
        "pass_rate": n_passed / n_total if n_total else 0.0,
        "positives_retained": tp,
        "positives_lost": fn,
        "recall": recall,
        "precision": precision,
        "f1": f1,
    }


def evaluate_gate_cv(X, y, params, n_splits=5, seed=RNG):
    """Honest out-of-fold validation: for each fold, fit the gate on the
    training split only, pick its threshold from that split's own OOB
    scores, then apply it to the held-out test split (data the gate never
    trained on or set its threshold from). Aggregates across all folds so
    every provider is scored exactly once, out-of-sample."""
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    passed_oof = np.zeros(len(y), dtype=bool)
    thresholds = []

    for train_idx, test_idx in skf.split(X, y):
        rf = _fit_gate(X[train_idx], y[train_idx], params, seed=seed)
        threshold, _ = _gate_threshold_from_oob(rf, X[train_idx], y[train_idx])
        thresholds.append(threshold)
        proba_test = rf.predict_proba(X[test_idx])[:, 1]
        passed_oof[test_idx] = proba_test >= threshold

    metrics = _gate_metrics(y, passed_oof, len(y))
    metrics["avg_threshold"] = float(np.mean(thresholds))
    return metrics


def train_final_cascade(provider_df: pd.DataFrame, feature_cols: list[str]):
    """Fit the final RF gate + XGBoost ranker on the FULL feature matrix.

    The gate uses the corrected RF_GATE_PARAMS. There is no train/test
    split here for the final artifact -- the whole dataset is the training
    set, since this is what gets deployed. Generalization is instead
    assessed separately via evaluate_gate_cv() before this is called.
    """
    X = provider_df[feature_cols].fillna(0).values
    y = provider_df["fraud_label"].values

    pos_rate = y.mean()
    neg_to_pos_ratio = (1 - pos_rate) / pos_rate

    # Stage 1: RandomForest gate. oob_score=True gives out-of-bag
    # probabilities so the gate threshold is calibrated on held-out
    # leaves rather than in-sample predictions (matches the notebook).
    rf_gate = _fit_gate(X, y, RF_GATE_PARAMS)
    gate_threshold, oob_proba = _gate_threshold_from_oob(rf_gate, X, y)
    gate_mask = oob_proba >= gate_threshold

    gate_eval_full = _gate_metrics(y, gate_mask, len(y))

    # Stage 2: XGBoost ranker, trained only on gate survivors. UNCHANGED.
    xgb_ranker = XGBClassifier(
        n_estimators=400,
        max_depth=5,
        learning_rate=0.05,
        scale_pos_weight=neg_to_pos_ratio,
        eval_metric="aucpr",
        random_state=RNG,
        subsample=0.8,
        colsample_bytree=0.8,
        tree_method="hist",
        verbosity=0,
    )
    xgb_ranker.fit(X[gate_mask], y[gate_mask])

    print(
        f"[full-data fit] Gate passed {gate_eval_full['providers_passed']}/{len(y)} "
        f"providers ({gate_eval_full['pass_rate']:.1%}); "
        f"recall={gate_eval_full['recall']:.1%} "
        f"(target {GATE_TARGET_RECALL:.0%}), lost {gate_eval_full['positives_lost']} fraudsters"
    )

    return rf_gate, xgb_ranker, gate_threshold, float(pos_rate), gate_eval_full


def format_report(gate_eval_before, gate_eval_after, gate_eval_cv) -> str:
    lines = []
    lines.append("=" * 72)
    lines.append("STAGE-1 RANDOM FOREST GATE -- EVALUATION REPORT")
    lines.append("=" * 72)

    lines.append("\n--- AFTER (corrected config, full-data self-consistency check) ---")
    e = gate_eval_after
    lines.append(f"Total providers:              {e['total_providers']:,}")
    lines.append(f"Positive providers:           {e['positive_providers']:,}")
    lines.append("")
    lines.append(f"Gate threshold:                {gate_eval_after.get('threshold', float('nan')):.4f}")
    lines.append(f"Target recall:                 {GATE_TARGET_RECALL:.0%}")
    lines.append(f"Actual recall:                 {e['recall']:.1%}")
    lines.append(f"Precision:                     {e['precision']:.1%}")
    lines.append(f"F1:                            {e['f1']:.3f}")
    lines.append("")
    lines.append(f"Providers passed:             {e['providers_passed']:,}")
    lines.append(f"Providers filtered:           {e['providers_filtered']:,}")
    lines.append(f"Pass rate:                     {e['pass_rate']:.1%}")
    lines.append("")
    lines.append(f"Positive providers retained:   {e['positives_retained']:,}")
    lines.append(f"Positive providers lost:       {e['positives_lost']:,}")

    lines.append("\n--- AFTER (honest 5-fold out-of-fold validation) ---")
    c = gate_eval_cv
    lines.append(f"Avg gate threshold across folds: {c['avg_threshold']:.4f}")
    lines.append(f"Out-of-fold recall:              {c['recall']:.1%}  (target {GATE_TARGET_RECALL:.0%})")
    lines.append(f"Out-of-fold precision:           {c['precision']:.1%}")
    lines.append(f"Out-of-fold F1:                  {c['f1']:.3f}")
    lines.append(f"Out-of-fold pass rate:           {c['pass_rate']:.1%}")
    lines.append(f"Out-of-fold positives lost:      {c['positives_lost']:,} / {c['positive_providers']:,}")

    lines.append("\n" + "=" * 72)
    lines.append("BEFORE vs AFTER  (full-data self-consistency check, same methodology)")
    lines.append("=" * 72)
    b = gate_eval_before
    lines.append(f"{'':<24}{'BEFORE':>14}{'AFTER':>14}")
    lines.append(f"{'Gate threshold':<24}{b.get('threshold', 0.0):>14.3f}{e.get('threshold', 0.0):>14.3f}")
    lines.append(f"{'Target recall':<24}{GATE_TARGET_RECALL:>13.0%} {GATE_TARGET_RECALL:>13.0%}")
    lines.append(f"{'Actual recall':<24}{b['recall']:>13.1%} {e['recall']:>13.1%}")
    lines.append(f"{'Providers passed':<24}{b['providers_passed']:>14,}{e['providers_passed']:>14,}")
    lines.append(f"{'Providers filtered':<24}{b['providers_filtered']:>14,}{e['providers_filtered']:>14,}")
    lines.append(f"{'Pass rate':<24}{b['pass_rate']:>13.1%} {e['pass_rate']:>13.1%}")
    lines.append(f"{'Positives lost':<24}{b['positives_lost']:>14,}{e['positives_lost']:>14,}")
    lines.append("=" * 72)

    return "\n".join(lines)


def main():
    if not PARQUET.exists():
        raise FileNotFoundError(
            f"Cached feature matrix not found at {PARQUET}. This script trains "
            "from that cache and does not regenerate it from raw data."
        )

    provider_df = pd.read_parquet(PARQUET)
    feature_cols = [c for c in provider_df.columns if c not in ("Provider", "fraud_label")]
    print(f"Loaded {provider_df.shape[0]} providers, {len(feature_cols)} features")

    X = provider_df[feature_cols].fillna(0).values
    y = provider_df["fraud_label"].values

    # BEFORE: reproduce the broken config's full-data self-consistency stats.
    rf_before = _fit_gate(X, y, RF_GATE_PARAMS_BEFORE)
    thresh_before, oob_before = _gate_threshold_from_oob(rf_before, X, y)
    gate_eval_before = _gate_metrics(y, oob_before >= thresh_before, len(y))
    gate_eval_before["threshold"] = thresh_before

    # AFTER: honest out-of-fold validation of the corrected config.
    print("Running 5-fold out-of-fold validation of the corrected gate...")
    gate_eval_cv = evaluate_gate_cv(X, y, RF_GATE_PARAMS)

    # AFTER: train the actual deployment artifact (full-data fit).
    rf_gate, xgb_ranker, gate_threshold, pos_rate, gate_eval_full = train_final_cascade(
        provider_df, feature_cols
    )
    gate_eval_full["threshold"] = gate_threshold

    report = format_report(gate_eval_before, gate_eval_full, gate_eval_cv)
    print("\n" + report)

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"\nSaved evaluation report to {REPORT_PATH}")

    artifact = {
        "rf_gate": rf_gate,
        "xgb_ranker": xgb_ranker,
        "gate_threshold": gate_threshold,
        "feature_cols": feature_cols,
        "gate_target_recall": GATE_TARGET_RECALL,
        "trained_rows": int(provider_df.shape[0]),
        "positive_rate": pos_rate,
        "rf_gate_params": RF_GATE_PARAMS,
        "gate_eval_full": gate_eval_full,
        "gate_eval_cv": gate_eval_cv,
    }
    joblib.dump(artifact, MODEL_PATH)
    print(f"Saved cascade model artifact to {MODEL_PATH}")


if __name__ == "__main__":
    main()
